Repository cyberark/conjur-cli-go, pull requests merged in 2023-04, with the labels that each got.

#120 Restore changes from #90, "Refactor PromptUI"
  .codeclimate.yml
  CHANGELOG.md
  NOTICES.txt
  go.mod
  go.sum
  pkg/clients/authn.go
  pkg/clients/clients.go
  pkg/clients/clients_test.go
  pkg/cmd/init.go
  pkg/cmd/init_test.go
  pkg/cmd/login.go
  pkg/cmd/login_test.go
  pkg/cmd/policy_test.go
  pkg/cmd/user.go
  pkg/cmd/user_test.go
  pkg/cmd/utils_test.go
  pkg/prompts/prompt.go
  pkg/utils/byte_buffered_reader.go
  pkg/utils/noop_closer.go
  pkg/utils/tls_test.go
  pkg/utils/write_closer.go
  pkg/utils/write_closer_test.go
Labels: kind/bug

#125 Update changelog for 8.0.6
  CHANGELOG.md
Labels: kind/release

#121 Remove netgo tag to fix Windows hosts file bug
  .goreleaser.yml
  CHANGELOG.md
Labels: kind/bug

#128 Make command help more consistent
  CHANGELOG.md
  pkg/cmd/authenticate.go
  pkg/cmd/hostfactory.go
  pkg/cmd/init.go
  pkg/cmd/login.go
  pkg/cmd/logout.go
  pkg/cmd/policy.go
  pkg/cmd/pubkeys.go
  pkg/cmd/resource.go
  pkg/cmd/role.go
  pkg/cmd/variable.go
  pkg/cmd/whoami.go
Labels: kind/enhancement, kind/quality

#130 Redact HTTP dumps
  CHANGELOG.md
  pkg/utils/http_dump_transport.go
  pkg/utils/http_dump_transport_test.go
Labels: security/medium, severity/medium, kind/security

#133 Reconsider TLS unit tests
  pkg/cmd/init_test.go
  pkg/utils/tls.go
  pkg/utils/tls_test.go
Labels: kind/quality

#132 Document authn-oidc flow
  docs/assets/authn-oidc.drawio
  docs/assets/authn-oidc.png
  docs/authn-oidc.md
Labels: kind/documentation
